dependencies = {
    layers: [
        {
            name: '../webcat/BasePage.js',
            resourceName: 'webcat.BasePage',
            dependencies: [
                "dojo.cache",
                "dojo.data.api.Identity",
                "dojo.data.util.simpleFetch",
                "dojo.dnd.Source",
                "dojo.NodeList-fx",
                "dojo.NodeList-traverse",
                "dijit.Dialog",
                "dijit.InlineEditBox",
                "dijit.Menu",
                "dijit.ProgressBar",
                "dijit.TitlePane",
                "dijit.Toolbar",
                "dijit.Tooltip",
                "dijit.Tree",
                "dijit.form.Button",
                "dijit.form.CheckBox",
                "dijit.form.ComboBox",
                "dijit.form.DateTextBox",
                "dijit.form.FilteringSelect",
                "dijit.form.Form",
                "dijit.form.NumberSpinner",
                "dijit.form.Select",
                "dijit.form.SimpleTextarea",
                "dijit.form.Slider",
                "dijit.form.Textarea",
                "dijit.form.TextBox",
                "dijit.form.TimeTextBox",
                "dijit.form.ValidationTextBox",
                "dojox.data.dom",
                "dojox.fx.scroll",
                "dojox.form.FileInput",
                "dojox.form.TimeSpinner",
                "webcat.global",
                "webcat.Blocker",
                "webcat.ComboBox",
                "webcat.ContentPane",
                "webcat.Dialog",
                "webcat.DropDownList",
                "webcat.FileInput",
                "webcat.Form",
                "webcat.Selector",
                "webcat.SearchField",
                "webcat.Spinner",
                "webcat.Table",
                "webcat.TableSource",
                "webcat.TitlePane",
                "webcat.ValidationResults"
            ]
        }
    ],
    prefixes: [
        [ "dijit", "../dijit" ],
        [ "dojox", "../dojox" ],
        [ "webcat", "../webcat" ]
    ]
};
