/*==========================================================================*\
 |  _Program.java
 |*-------------------------------------------------------------------------*|
 |  Created by eogenerator
 |  DO NOT EDIT.  Make changes to Program.java instead.
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2009 Virginia Tech
 |
 |  This file is part of Web-CAT.
 |
 |  Web-CAT is free software; you can redistribute it and/or modify
 |  it under the terms of the GNU Affero General Public License as published
 |  by the Free Software Foundation; either version 3 of the License, or
 |  (at your option) any later version.
 |
 |  Web-CAT is distributed in the hope that it will be useful,
 |  but WITHOUT ANY WARRANTY; without even the implied warranty of
 |  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |  GNU General Public License for more details.
 |
 |  You should have received a copy of the GNU Affero General Public License
 |  along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package org.webcat.outcomesmeasurement;

import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;
import er.extensions.eof.ERXEOControlUtilities;
import er.extensions.eof.ERXKey;
import org.apache.log4j.Logger;

// -------------------------------------------------------------------------
/**
 * An automatically generated EOGenericRecord subclass.  DO NOT EDIT.
 * To change, use EOModeler, or make additions in
 * Program.java.
 *
 * @author Generated by eogenerator
 * @version version suppressed to control auto-generation
 */
public abstract class _Program
    extends er.extensions.eof.ERXGenericRecord
{
    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new _Program object.
     */
    public _Program()
    {
        super();
    }


    // ----------------------------------------------------------
    /**
     * A static factory method for creating a new
     * Program object given required
     * attributes and relationships.
     * @param editingContext The context in which the new object will be
     * inserted
     * @param departmentValue
     * @return The newly created object
     */
    public static Program create(
        EOEditingContext editingContext,
        org.webcat.core.Department departmentValue
        )
    {
        Program eoObject = (Program)
            EOUtilities.createAndInsertInstance(
                editingContext,
                _Program.ENTITY_NAME);
        eoObject.setDepartmentRelationship(departmentValue);
        return eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Get a local instance of the given object in another editing context.
     * @param editingContext The target editing context
     * @param eo The object to import
     * @return An instance of the given object in the target editing context
     */
    public static Program localInstance(
        EOEditingContext editingContext, Program eo)
    {
        return (eo == null)
            ? null
            : (Program)EOUtilities.localInstanceOfObject(
                editingContext, eo);
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static Program forId(
        EOEditingContext ec, int id )
    {
        Program obj = null;
        if (id > 0)
        {
            NSArray<Program> results =
                objectsMatchingValues(ec, "id", new Integer(id));
            if (results != null && results.count() > 0)
            {
                obj = results.objectAtIndex(0);
            }
        }
        return obj;
    }


    // ----------------------------------------------------------
    /**
     * Look up an object by id number.  Assumes the editing
     * context is appropriately locked.
     * @param ec The editing context to use
     * @param id The id to look up
     * @return The object, or null if no such id exists
     */
    public static Program forId(
        EOEditingContext ec, String id )
    {
        return forId( ec, er.extensions.foundation.ERXValueUtilities.intValue( id ) );
    }


    //~ Constants (for key names) .............................................

    // Attributes ---
    public static final String NAME_KEY = "name";
    public static final ERXKey<String> name =
        new ERXKey<String>(NAME_KEY);
    // To-one relationships ---
    public static final String DEPARTMENT_KEY = "department";
    public static final ERXKey<org.webcat.core.Department> department =
        new ERXKey<org.webcat.core.Department>(DEPARTMENT_KEY);
    // To-many relationships ---
    public static final String OUTCOME_SETS_KEY = "outcomeSets";
    public static final ERXKey<org.webcat.outcomesmeasurement.OutcomeSet> outcomeSets =
        new ERXKey<org.webcat.outcomesmeasurement.OutcomeSet>(OUTCOME_SETS_KEY);
    public static final String PROGRAM_OUTCOMES_KEY = "programOutcomes";
    public static final ERXKey<org.webcat.outcomesmeasurement.ProgramOutcome> programOutcomes =
        new ERXKey<org.webcat.outcomesmeasurement.ProgramOutcome>(PROGRAM_OUTCOMES_KEY);
    // Fetch specifications ---
    public static final String ENTITY_NAME = "Program";


    //~ Methods ...............................................................

    // ----------------------------------------------------------
    /**
     * Get a local instance of this object in another editing context.
     * @param editingContext The target editing context
     * @return An instance of this object in the target editing context
     */
    public Program localInstance(EOEditingContext editingContext)
    {
        return (Program)EOUtilities.localInstanceOfObject(
            editingContext, this);
    }


    // ----------------------------------------------------------
    /**
     * Get a list of changes between this object's current state and the
     * last committed version.
     * @return a dictionary of the changes that have not yet been committed
     */
    @SuppressWarnings("unchecked")
    public NSDictionary<String, Object> changedProperties()
    {
        return changesFromSnapshot(
            editingContext().committedSnapshotForObject(this) );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>id</code> value.
     * @return the value of the attribute
     */
    public Number id()
    {
        try
        {
            return (Number)EOUtilities.primaryKeyForObject(
                editingContext() , this ).objectForKey( "id" );
        }
        catch (Exception e)
        {
            return er.extensions.eof.ERXConstant.ZeroInteger;
        }
    }

    // ----------------------------------------------------------
    /**
     * Retrieve this object's <code>name</code> value.
     * @return the value of the attribute
     */
    public String name()
    {
        return (String)storedValueForKey( "name" );
    }


    // ----------------------------------------------------------
    /**
     * Change the value of this object's <code>name</code>
     * property.
     *
     * @param value The new value for this property
     */
    public void setName( String value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setName("
                + value + "): was " + name() );
        }
        takeStoredValueForKey( value, "name" );
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entity pointed to by the <code>department</code>
     * relationship.
     * @return the entity in the relationship
     */
    public org.webcat.core.Department department()
    {
        return (org.webcat.core.Department)storedValueForKey( "department" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>department</code>
     * relationship (DO NOT USE--instead, use
     * <code>setDepartmentRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void setDepartment( org.webcat.core.Department value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setDepartment("
                + value + "): was " + department() );
        }
        takeStoredValueForKey( value, "department" );
    }


    // ----------------------------------------------------------
    /**
     * Set the entity pointed to by the <code>department</code>
     * relationship.  This method is a type-safe version of
     * <code>addObjectToBothSidesOfRelationshipWithKey()</code>.
     *
     * @param value The new entity to relate to
     */
    public void setDepartmentRelationship(
        org.webcat.core.Department value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setDepartmentRelationship("
                + value + "): was " + department() );
        }
        if ( value == null )
        {
            org.webcat.core.Department object = department();
            if ( object != null )
                removeObjectFromBothSidesOfRelationshipWithKey( object, "department" );
        }
        else
        {
            addObjectToBothSidesOfRelationshipWithKey( value, "department" );
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>outcomeSets</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.outcomesmeasurement.OutcomeSet> outcomeSets()
    {
        return (NSArray)storedValueForKey( "outcomeSets" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>outcomeSets</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setOutcomeSets( NSMutableArray<org.webcat.outcomesmeasurement.OutcomeSet>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setOutcomeSets("
                + value + "): was " + outcomeSets() );
        }
        takeStoredValueForKey( value, "outcomeSets" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>outcomeSets</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToOutcomeSetsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToOutcomeSets( org.webcat.outcomesmeasurement.OutcomeSet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToOutcomeSets("
                + value + "): was " + outcomeSets() );
        }
        NSMutableArray<org.webcat.outcomesmeasurement.OutcomeSet> array =
            (NSMutableArray<org.webcat.outcomesmeasurement.OutcomeSet>)outcomeSets();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>outcomeSets</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromOutcomeSetsRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromOutcomeSets( org.webcat.outcomesmeasurement.OutcomeSet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromOutcomeSets("
                + value + "): was " + outcomeSets() );
        }
        NSMutableArray<org.webcat.outcomesmeasurement.OutcomeSet> array =
            (NSMutableArray<org.webcat.outcomesmeasurement.OutcomeSet>)outcomeSets();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>outcomeSets</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToOutcomeSetsRelationship( org.webcat.outcomesmeasurement.OutcomeSet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToOutcomeSetsRelationship("
                + value + "): was " + outcomeSets() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "outcomeSets" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>outcomeSets</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromOutcomeSetsRelationship( org.webcat.outcomesmeasurement.OutcomeSet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromOutcomeSetsRelationship("
                + value + "): was " + outcomeSets() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "outcomeSets" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>outcomeSets</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.outcomesmeasurement.OutcomeSet createOutcomeSetsRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createOutcomeSetsRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "OutcomeSet" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "outcomeSets" );
        return (org.webcat.outcomesmeasurement.OutcomeSet)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>outcomeSets</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteOutcomeSetsRelationship( org.webcat.outcomesmeasurement.OutcomeSet value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteOutcomeSetsRelationship("
                + value + "): was " + outcomeSets() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "outcomeSets" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>outcomeSets</code> relationship.
     */
    public void deleteAllOutcomeSetsRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllOutcomeSetsRelationships(): was "
                + outcomeSets() );
        }
        for (org.webcat.outcomesmeasurement.OutcomeSet object : outcomeSets())
        {
            deleteOutcomeSetsRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the entities pointed to by the <code>programOutcomes</code>
     * relationship.
     * @return an NSArray of the entities in the relationship
     */
    @SuppressWarnings("unchecked")
    public NSArray<org.webcat.outcomesmeasurement.ProgramOutcome> programOutcomes()
    {
        return (NSArray)storedValueForKey( "programOutcomes" );
    }


    // ----------------------------------------------------------
    /**
     * Replace the list of entities pointed to by the
     * <code>programOutcomes</code> relationship.
     *
     * @param value The new set of entities to relate to
     */
    public void setProgramOutcomes( NSMutableArray<org.webcat.outcomesmeasurement.ProgramOutcome>  value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "setProgramOutcomes("
                + value + "): was " + programOutcomes() );
        }
        takeStoredValueForKey( value, "programOutcomes" );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>programOutcomes</code>
     * relationship (DO NOT USE--instead, use
     * <code>addToProgramOutcomesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The new entity to relate to
     */
    public void addToProgramOutcomes( org.webcat.outcomesmeasurement.ProgramOutcome value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToProgramOutcomes("
                + value + "): was " + programOutcomes() );
        }
        NSMutableArray<org.webcat.outcomesmeasurement.ProgramOutcome> array =
            (NSMutableArray<org.webcat.outcomesmeasurement.ProgramOutcome>)programOutcomes();
        willChange();
        array.addObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>programOutcomes</code>
     * relationship (DO NOT USE--instead, use
     * <code>removeFromProgramOutcomesRelationship()</code>.
     * This method is provided for WebObjects use.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromProgramOutcomes( org.webcat.outcomesmeasurement.ProgramOutcome value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "RemoveFromProgramOutcomes("
                + value + "): was " + programOutcomes() );
        }
        NSMutableArray<org.webcat.outcomesmeasurement.ProgramOutcome> array =
            (NSMutableArray<org.webcat.outcomesmeasurement.ProgramOutcome>)programOutcomes();
        willChange();
        array.removeObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Add a new entity to the <code>programOutcomes</code>
     * relationship.
     *
     * @param value The new entity to relate to
     */
    public void addToProgramOutcomesRelationship( org.webcat.outcomesmeasurement.ProgramOutcome value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "addToProgramOutcomesRelationship("
                + value + "): was " + programOutcomes() );
        }
        addObjectToBothSidesOfRelationshipWithKey(
            value, "programOutcomes" );
    }


    // ----------------------------------------------------------
    /**
     * Remove a specific entity from the <code>programOutcomes</code>
     * relationship.
     *
     * @param value The entity to remove from the relationship
     */
    public void removeFromProgramOutcomesRelationship( org.webcat.outcomesmeasurement.ProgramOutcome value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "removeFromProgramOutcomesRelationship("
                + value + "): was " + programOutcomes() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "programOutcomes" );
    }


    // ----------------------------------------------------------
    /**
     * Create a brand new object that is a member of the
     * <code>programOutcomes</code> relationship.
     *
     * @return The new entity
     */
    public org.webcat.outcomesmeasurement.ProgramOutcome createProgramOutcomesRelationship()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "createProgramOutcomesRelationship()" );
        }
        EOClassDescription eoClassDesc = EOClassDescription
            .classDescriptionForEntityName( "ProgramOutcome" );
        EOEnterpriseObject eoObject = eoClassDesc
            .createInstanceWithEditingContext( editingContext(), null );
        editingContext().insertObject( eoObject );
        addObjectToBothSidesOfRelationshipWithKey(
            eoObject, "programOutcomes" );
        return (org.webcat.outcomesmeasurement.ProgramOutcome)eoObject;
    }


    // ----------------------------------------------------------
    /**
     * Remove and then delete a specific entity that is a member of the
     * <code>programOutcomes</code> relationship.
     *
     * @param value The entity to remove from the relationship and then delete
     */
    public void deleteProgramOutcomesRelationship( org.webcat.outcomesmeasurement.ProgramOutcome value )
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteProgramOutcomesRelationship("
                + value + "): was " + programOutcomes() );
        }
        removeObjectFromBothSidesOfRelationshipWithKey(
            value, "programOutcomes" );
        editingContext().deleteObject( value );
    }


    // ----------------------------------------------------------
    /**
     * Remove (and then delete, if owned) all entities that are members of the
     * <code>programOutcomes</code> relationship.
     */
    public void deleteAllProgramOutcomesRelationships()
    {
        if (log.isDebugEnabled())
        {
            log.debug( "deleteAllProgramOutcomesRelationships(): was "
                + programOutcomes() );
        }
        for (org.webcat.outcomesmeasurement.ProgramOutcome object : programOutcomes())
        {
            deleteProgramOutcomesRelationship(object);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a fetch specification.
     *
     * @param context The editing context to use
     * @param fspec The fetch specification to use
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<Program> objectsWithFetchSpecification(
        EOEditingContext context,
        EOFetchSpecification fspec)
    {
        return context.objectsWithFetchSpecification(fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<Program> allObjects(
        EOEditingContext context)
    {
        return objectsMatchingQualifier(context, null, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<Program> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier)
    {
        return objectsMatchingQualifier(context, qualifier, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a qualifier and sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings The sort orderings to use
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<Program> objectsMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        EOFetchSpecification fspec = new EOFetchSpecification(
            ENTITY_NAME, qualifier, sortOrderings);
        fspec.setUsesDistinct(true);
        return objectsWithFetchSpecification(context, fspec);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a qualifier, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     * @param sortOrderings the sort orderings
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static Program firstObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier,
        NSArray<EOSortOrdering> sortOrderings)
    {
        NSArray<Program> results =
            objectsMatchingQualifier(context, qualifier, sortOrderings);
        return (results.size() > 0)
            ? results.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the single entity that was retrieved
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static Program uniqueObjectMatchingQualifier(
        EOEditingContext context,
        EOQualifier qualifier) throws EOUtilities.MoreThanOneException
    {
        NSArray<Program> results =
            objectsMatchingQualifier(context, qualifier);
        if (results.size() > 1)
        {
            throw new EOUtilities.MoreThanOneException(null);
        }
        return (results.size() > 0)
            ? results.get(0)
            : null;
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return an NSArray of the entities retrieved
     */
    public static NSArray<Program> objectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return objectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve objects using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return an NSArray of the entities retrieved
     */
    @SuppressWarnings("unchecked")
    public static NSArray<Program> objectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return EOUtilities.objectsMatchingValues(context, ENTITY_NAME,
            keysAndValues);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static Program firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return firstObjectMatchingValues(
            context, sortOrderings, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieves the first object that matches a set of keys and values, when
     * sorted with the specified sort orderings.
     *
     * @param context The editing context to use
     * @param sortOrderings the sort orderings
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the first entity that was retrieved, or null if there was none
     */
    public static Program firstObjectMatchingValues(
        EOEditingContext context,
        NSArray<EOSortOrdering> sortOrderings,
        NSDictionary<String, Object> keysAndValues)
    {
        EOFetchSpecification fspec = new EOFetchSpecification(
            ENTITY_NAME,
            EOQualifier.qualifierToMatchAllValues(keysAndValues),
            sortOrderings);
        fspec.setFetchLimit(1);

        NSArray<Program> result =
            objectsWithFetchSpecification( context, fspec );

        if ( result.count() == 0 )
        {
            return null;
        }
        else
        {
            return result.objectAtIndex(0);
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve a single object using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static Program uniqueObjectMatchingValues(
        EOEditingContext context,
        Object... keysAndValues) throws EOUtilities.MoreThanOneException
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return uniqueObjectMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve an object using a dictionary of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the single entity that was retrieved, or null if there was none
     *
     * @throws EOUtilities.MoreThanOneException
     *     if there is more than one matching object
     */
    public static Program uniqueObjectMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
        throws EOUtilities.MoreThanOneException
    {
        try
        {
            return (Program)EOUtilities.objectMatchingValues(
                context, ENTITY_NAME, keysAndValues);
        }
        catch (EOObjectNotAvailableException e)
        {
            return null;
        }
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of all objects of this type.
     *
     * @param context The editing context to use
     *
     * @return the count of all objects
     */
    public static int countOfAllObjects(EOEditingContext context)
    {
        return countOfObjectsMatchingQualifier(context, null);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects that match a qualifier.
     *
     * @param context The editing context to use
     * @param qualifier The qualifier to use
     *
     * @return the count of objects matching the qualifier
     */
    public static int countOfObjectsMatchingQualifier(
        EOEditingContext context, EOQualifier qualifier)
    {
        return ERXEOControlUtilities.objectCountWithQualifier(
                context, ENTITY_NAME, qualifier);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a list of keys and values to match.
     *
     * @param context The editing context to use
     * @param keysAndValues a list of keys and values to match, alternating
     *     "key", "value", "key", "value"...
     *
     * @return the count of objects that match the specified values
     */
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        Object... keysAndValues)
    {
        if (keysAndValues.length % 2 != 0)
        {
            throw new IllegalArgumentException("There should a value " +
                "corresponding to every key that was passed.");
        }

        NSMutableDictionary<String, Object> valueDictionary =
            new NSMutableDictionary<String, Object>();

        for (int i = 0; i < keysAndValues.length; i += 2)
        {
            Object key = keysAndValues[i];
            Object value = keysAndValues[i + 1];

            if (!(key instanceof String))
            {
                throw new IllegalArgumentException("Keys should be strings.");
            }

            valueDictionary.setObjectForKey(value, key);
        }

        return countOfObjectsMatchingValues(context, valueDictionary);
    }


    // ----------------------------------------------------------
    /**
     * Retrieve the count of objects using a dictionary of keys and values to
     * match.
     *
     * @param context The editing context to use
     * @param keysAndValues a dictionary of keys and values to match
     *
     * @return the count of objects that matched the specified values
     */
    @SuppressWarnings("unchecked")
    public static int countOfObjectsMatchingValues(
        EOEditingContext context,
        NSDictionary<String, Object> keysAndValues)
    {
        return countOfObjectsMatchingQualifier(context,
                EOQualifier.qualifierToMatchAllValues(keysAndValues));
    }


    // ----------------------------------------------------------
    /**
     * Produce a string representation of this object.  This implementation
     * calls UserPresentableDescription(), which uses WebObjects' internal
     * mechanism to print out the visible fields of this object.  Normally,
     * subclasses would override userPresentableDescription() to change
     * the way the object is printed.
     *
     * @return A string representation of the object's value
     */
    public String toString()
    {
        return userPresentableDescription();
    }


    //~ Instance/static variables .............................................

    static Logger log = Logger.getLogger( Program.class );
}
