/*==========================================================================*\
 |  $Id$
 |*-------------------------------------------------------------------------*|
 |  Copyright (C) 2006-2009 Virginia Tech 
 |
 |	This file is part of Web-CAT Eclipse Plugins.
 |
 |	Web-CAT is free software; you can redistribute it and/or modify
 |	it under the terms of the GNU General Public License as published by
 |	the Free Software Foundation; either version 2 of the License, or
 |	(at your option) any later version.
 |
 |	Web-CAT is distributed in the hope that it will be useful,
 |	but WITHOUT ANY WARRANTY; without even the implied warranty of
 |	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 |	GNU General Public License for more details.
 |
 |	You should have received a copy of the GNU General Public License
 |	along with Web-CAT; if not, see <http://www.gnu.org/licenses/>.
\*==========================================================================*/

package net.sf.webcat.eclipse.cxxtest.model;

/**
 * The base class for all CxxTest results.
 * 
 * @author  Tony Allevato (Virginia Tech Computer Science)
 * @author  latest changes by: $Author$
 * @version $Revision$ $Date$
 */
public interface ICxxTestBase
{
	/**
	 * A message that is purely informational, such as TS_TRACE().
	 */
	static final int STATUS_OK = 0;
	
	/**
	 * A message that indicates a warning, but not a problem severe enough to
	 * be considered a failed test.  Currently only generated by a
	 * user-specified TS_WARN() directive.
	 */
	static final int STATUS_WARNING = 1;

	/**
	 * A message indicating a failed assertion, usually because the expected
	 * result of an expression in one of the TS_ASSERT_* macros was not
	 * satisfied.
	 */
	static final int STATUS_FAILED = 2;

	/**
	 * A message indicating an error more severe than a failed assertion.
	 * These can occur if, for example, a signal is trapped during the
	 * execution of a test method.
	 */
	static final int STATUS_ERROR = 3;

	/**
	 * Returns the parent object.
	 * 
	 * @return the parent of this CxxTest object.
	 */
	ICxxTestBase getParent();

	/**
	 * Returns the status code of this CxxTest object. Assertion objects
	 * return their own status code; test methods and test suites return the
	 * most severe status code of all their children.
	 * 
	 * @return the status code of this object, from the STATUS_* constants
	 *     defined in this interface.
	 */
	int getStatus();
}
